version: 2
project_name: uploadserver

before:
  hooks:
    - go mod tidy

builds:
  - id: uploadserver
    main: .
    binary: uploadserver
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X uploadserver/internal.Version={{.Version}}
      - -X uploadserver/internal.Commit={{.Commit}}
      - -X uploadserver/internal.Date={{.Date}}
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: checksums.txt
  algorithm: sha256

sboms:
  - artifacts: archive

snapshot:
  version_template: "{{ .Version }}-next"

changelog:
  sort: asc
  use: git
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug fixes
      regexp: '^.*?fix(\(.+\))??!?:.+$'
      order: 1
    - title: Other changes
      order: 999

release:
  draft: false
  prerelease: auto
